[project]
name = "credential-registry"
description = "On-chain credentials and certificates"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
[contracts.credential-registry]
path = "contracts/credential-registry.clar"
clarity_version = 2
epoch = 2.4
